apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguation
resources:
  - resources:
      - secrets
    providers:
      - identity: {}
      - aesgcm:
        keys:
          - name: key1
            secret: xdkfs
          - name: key2
            secret: xxdf
      - aescbc:
        keys:
          - name: key1 
            secret: xx
      - secretbox:
        keys:
          - name: k1 
            secret: x
      - kms: 
        name: mykmsPlugin
        endpoint: unix://xxx.sock
        cachesize: 100
