apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-app
  namespace: default
  labels:
    app: crd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crd-app
  template:
    metadata:
      labels:
        app: crd-app
    spec:
      containers:
        - name: crd-app
          image: nginx
          ports:
            - containerPort: 8080