FROM golang:1.20 as builder

WORKDIR /home

COPY . .
# RUN ls 1>&2
# RUN go env -w GOPROXY=https://goproxy.cn,direct

#RUN go get k8s.io/client-go@v0.23.14 
# RUN go mod tidy # 修改GOPROXY 还是拉不下来，最后在宿主机执行go mod vendor，来完成的
RUN CGO_ENABLED=0 go build -o ingress-manager main.go

FROM alpine:3.15.3

USER www

WORKDIR /

COPY --from=builder /home/ingress-manager .

CMD ["./ingress-manager"]