---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mygroup.mfx.co
  resources:
  - mykinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.mfx.co
  resources:
  - mykinds/finalizers
  verbs:
  - update
- apiGroups:
  - mygroup.mfx.co
  resources:
  - mykinds/status
  verbs:
  - get
  - patch
  - update
