apiVersion: mygroup.mfx.co/v1beta1
kind: MyKind
metadata:
  labels:
    app.kubernetes.io/name: mykind
    app.kubernetes.io/instance: mykind-sample
    app.kubernetes.io/part-of: project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: project
  name: mykind-sample
spec:
  # TODO(user): Add fields here
